# Generated by Django 4.2.6 on 2023-10-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0002_alter_person_options_remove_person_surname_and_more"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={},
        ),
        migrations.AddField(
            model_name="team",
            name="persons",
            field=models.ManyToManyField(to="persons.person"),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
