# Generated by Django 4.2.6 on 2023-10-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={},
        ),
        migrations.RemoveField(
            model_name="person",
            name="surname",
        ),
        migrations.RemoveField(
            model_name="person",
            name="team",
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
